version: '3'

services:
  django_app:
    build: application/.
    ports:
      - 80:80
    volumes:
      - ./application/:/application/
    working_dir: /application/dealsmaster/
    depends_on:
      - redis
      - postgres
  redis:
    image: redis
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dealsmaster
      - PGDATA=/var/lib/postgresql/data/pgdata